<!-- Pin to top left corner -->
<header class="absolute top-0 left-0 h-12 w-18 p-4">
  <strong>Anacleto's Blog</strong>
  @template.fragment.header.item(content = "🧑‍💻", tooltipText = "Tech Blog", tooltipPosition = "bottom", reference = "techButton")
  @template.fragment.header.item(content = "🏛", tooltipText = "Mythology Blog", tooltipPosition = "bottom", reference = "mythButton")
  @template.fragment.header.item(content = "🌙", tooltipText = "Theme Toggle", tooltipPosition = "bottom", reference = "themeButton")
</header>
